name: Build and Publish on DockerHub

on:
  issue_comment:
    types: [created]

jobs:
  build-and-publish:
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'dockerhub')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

     # Gera a tag com data, hora, minutos e segundos
      - name: Set tag name with timestamp
        id: tagname
        run: echo "::set-output name=tag::$(date +'%Y-%m-%d-%H-%M-%S')"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: sebastiaof/golang-app:${{ steps.tagname.outputs.tag }}